using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace POS.ViewControls
{
    public partial class DashboardViewControl : DevExpress.XtraEditors.XtraUserControl
    {
        POSDataClassesDataContext db;
        public DashboardViewControl()
        {
            db = new POSDataClassesDataContext();
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            invoicesBindingSource.DataSource = new POS.POSDataClassesDataContext().Invoices;
        }

        private void DashboardViewControl_Load(object sender, EventArgs e)
        {
            SetTopSellingProduct();
        }

        private void SetTopSellingProduct()
        {
            var topSelling = (from p in db.Products
                             join i in (from item in db.InvoiceItems
                                        group item by item.Product_ProdId into g
                                        select new { id = g.Key, Quantity = g.Sum(item => item.Quantity) })
                             on p.ProdId equals i.id
                             orderby i.Quantity descending
                             select new { p.ProdName, i.Quantity }).Take(10);
            BindingSource sellingBindingSource = new BindingSource();
            sellingBindingSource.DataSource = topSelling;
            TopSellingGridControl.DataSource = sellingBindingSource;
            TopSellingGridControl.RefreshDataSource();

        }
    }
}
