using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace POS.ViewControls
{
    public partial class DashboardViewControl : DevExpress.XtraEditors.XtraUserControl
    {
        POSDataClassesDataContext db;
        public DashboardViewControl()
        {
            db = new POSDataClassesDataContext();
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            invoicesBindingSource.DataSource = new POS.POSDataClassesDataContext().Invoices;
        }

        private void DashboardViewControl_Load(object sender, EventArgs e)
        {
            SetTopSellingProduct();
            SetTodaySummery();
        }

        private void SetTopSellingProduct()
        {
            var topSelling = (from p in db.Products
                             join i in (from item in db.InvoiceItems
                                        group item by item.Product_ProdId into g
                                        select new { id = g.Key, Quantity = g.Sum(item => item.Quantity) })
                             on p.ProdId equals i.id
                             orderby i.Quantity descending
                             select new { p.ProdName, i.Quantity }).Take(10);
            BindingSource sellingBindingSource = new BindingSource
            {
                DataSource = topSelling
            };
            TopSellingGridControl.DataSource = sellingBindingSource;
            TopSellingGridControl.RefreshDataSource();
        }
        private void SetTodaySummery()
        {
            var summeryResult = db.GetTodaySummery(DateTime.Now.Date).SingleOrDefault();
            if (summeryResult != null)
            {
                TotalSaleLabel.Text = String.Format("$ {0}", summeryResult.TotalSale);
                TotalCustServedLabel.Text = summeryResult.CustomerServed.ToString();
                TotalInvoiceLabel.Text = summeryResult.TotalInvoice.ToString();
            }

            var totalProductSale = db.GetTodayTotalProductSale(DateTime.Now.Date).SingleOrDefault();
            if(totalProductSale != null)
            {
                TotalProductSoldLabel.Text = totalProductSale.TotalProduct.ToString();
            }
        }
    }
}
