using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Tile;
using DevExpress.XtraGrid.Views.Tile.ViewInfo;

namespace POS.ViewControls
{
    public partial class SaleViewControl : DevExpress.XtraEditors.XtraUserControl
    {
        public SaleViewControl()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            productsBindingSource.DataSource = new POS.POSDataClassesDataContext().Products;
            // This line of code is generated by Data Source Configuration Wizard
            customersBindingSource.DataSource = new POS.POSDataClassesDataContext().Customers;
            // This line of code is generated by Data Source Configuration Wizard
            paymentTypesBindingSource.DataSource = new POS.POSDataClassesDataContext().PaymentTypes;
        }

        private void ProductsTileView_ItemClick(object sender, TileViewItemClickEventArgs e)
        {
            
            string code = e.Item.Elements[1].Text;
            string id = e.Item.Elements[10].Text;
            string name = e.Item.Elements[6].Text;
            string price = e.Item.Elements[7].Text;
            string stock = e.Item.Elements[8].Text;
            string discount = e.Item.Elements[9].Text;
            Console.WriteLine(code);
            Console.WriteLine(name);
            Console.WriteLine(price);
            Console.WriteLine(stock);
            Console.WriteLine(discount);
            Console.WriteLine(id);

        }
    }
}
