using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace POS.ViewControls
{
    public partial class ServiceViewControl : DevExpress.XtraEditors.XtraUserControl
    {
        public ServiceViewControl()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            servicesBindingSource.DataSource = new POS.POSDataClassesDataContext().Services;
        }
    }
}
