using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraGrid.Views.Grid;

namespace IslahGroupInventory.ViewControls
{
    public partial class CustomersControl : UserControl
    {
        InventoryDataClassesDataContext dbContext;
        public CustomersControl()
        {
            dbContext = new InventoryDataClassesDataContext();
            InitializeComponent();
        }

        private void CustomersControl_Load(object sender, EventArgs e)
        {
            LoadNewCustomerCode();
        }

        private void LoadNewCustomerCode()
        {
            textBoxICCode.Text = String.Format("CUST{0:D5}", dbContext.GetNextCustomerCode());
        }

        private void LoadTotalCustomerCounter()
        {
            var totalCustomer = dbContext.Customers.Count();
            labelTotalCustomers.Text = totalCustomer.ToString();
        }

        private void LoadCustomersGridView()
        {
            // This line of code is generated by Data Source Configuration Wizard
            //customersBindingSource.DataSource = new InventoryDataClassesDataContext().Customers;
            //gridControlCustomers.RefreshDataSource();
        }

        private void buttonAddCustomer_Click(object sender, EventArgs e)
        {
            // TODO: Customer add validation

            dbContext.Customers.InsertOnSubmit(new Customer()
            {
                CustCode = textBoxICCode.Text,
                CustName = textBoxICName.Text,
                Address = textBoxICAddress.Text,
                ContactNo = textBoxICContactNo.Text,
                Email = textBoxICEmail.Text,
                Remark = textBoxICRemarks.Text,
                Branch_BranchId = 1
            });

            dbContext.SubmitChanges();
            //LoadCustomerPage();
            LoadNewCustomerCode();
        }

        private void gridViewCustomer_ValidateRow(object sender, DevExpress.XtraGrid.Views.Base.ValidateRowEventArgs e)
        {
            GridView view = sender as GridView;
            var row = view.GetRow(e.RowHandle);
            string custCode = view.GetRowCellValue(e.RowHandle, "CustCode").ToString();

            var customer = dbContext.Customers.SingleOrDefault(c => c.CustCode == custCode);
            var rowCustomer = row as Customer;

            customer.CustName = rowCustomer.CustName;
            customer.Address = rowCustomer.Address;
            customer.ContactNo = rowCustomer.ContactNo;
            customer.Email = rowCustomer.Email;
            customer.Remark = rowCustomer.Remark;

            dbContext.SubmitChanges();
        }


        // Customers Tab Methods End
    }
}
