using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace IslahGroupInventory.ViewControls
{
    public partial class ProductsControl : UserControl
    {
        InventoryDataClassesDataContext dbContext;
        public ProductsControl()
        {
            dbContext = new InventoryDataClassesDataContext();
            InitializeComponent();
        }
        private void LoadNewProductCode()
        {
            textBoxProdCode.Text = String.Format("PROD{0:D5}", dbContext.GetNextProductCode());
        }

        private void LoadProductCategory()
        {
            //productCategoryBindingSource.DataSource = new InventoryDataClassesDataContext().SubCategories;
            //comboBoxUPCategory.DataSource = productCategoryBindingSource;
        }

        private void LoadProductsGridView()
        {
            // This line of code is generated by Data Source Configuration Wizard
            //productsBindingSource.DataSource = new InventoryDataClassesDataContext().Products;
            //gridControlProducts.RefreshDataSource();
        }

        private void buttonAddProduct_Click(object sender, EventArgs e)
        {
            // TODO: Validation of the Add Product
            string prodCode = textBoxProdCode.Text;
            string prodName = textBoxName.Text;
            string desc = textBoxDescription.Text;
            string category = comboBoxCategory.Text;
            string sellPrice = textBoxSPrice.Text;
            string rp = textBoxRPoint.Text;
            string discount = textBoxDiscount.Text;
            string stock = textBoxStock.Text;

            Product newProduct = new Product()
            {
                ProdCode = prodCode,
                ProdName = prodName,
                Description = desc,
                SubCategory_Name = category,
                SellingPrice = Convert.ToDecimal(sellPrice),
                ReOrderPoint = Convert.ToInt16(rp),
                Discount = Convert.ToDecimal(discount),
                Stock = Convert.ToInt32(stock),
                Branch_BranchId = 1
            };
            dbContext.Products.InsertOnSubmit(newProduct);
            dbContext.SubmitChanges();
            Console.WriteLine(newProduct.ProdId);
            LoadProductsGridView();
            LoadNewProductCode();
        }

        private void buttonUpdateProduct_Click(object sender, EventArgs e)
        {
            string productCode = textBoxUPCode.Text;
            var product = dbContext.Products.SingleOrDefault(p => p.ProdCode == productCode);
            product.ProdName = textBoxUPName.Text;
            product.Description = textBoxUPDescription.Text;
            product.SubCategory_Name = comboBoxUPCategory.Text;
            product.SellingPrice = Convert.ToDecimal(textBoxUPSPrice.Text);
            product.ReOrderPoint = Convert.ToInt16(textBoxUPRPoint.Text);
            product.Discount = Convert.ToDecimal(textBoxUPDiscount.Text);

            dbContext.SubmitChanges();
            LoadProductsGridView();

            XtraMessageBox.Show("Product Updated!!", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void buttonUPLoad_Click(object sender, EventArgs e)
        {
            string productCode = textBoxUPCode.Text;
            var product = dbContext.Products.SingleOrDefault(p => p.ProdCode == productCode);
            if (product != null)
            {
                textBoxUPName.Text = product.ProdName;
                textBoxUPDescription.Text = product.Description;
                comboBoxUPCategory.Text = product.SubCategory_Name;
                textBoxUPSPrice.Text = product.SellingPrice.ToString();
                textBoxUPRPoint.Text = product.ReOrderPoint.ToString();
                textBoxUPDiscount.Text = product.Discount.ToString();
                textBoxUPStock.Text = product.Stock.ToString();
                buttonUpdateProduct.Enabled = true;
            }
            else
            {
                XtraMessageBox.Show("No product found!!", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void buttonProductDelete_Click(object sender, EventArgs e)
        {
            string productCode = textBoxDPCode.Text;
            var product = dbContext.Products.SingleOrDefault(p => p.ProdCode == productCode);

            if (product != null)
            {
                dbContext.Products.DeleteOnSubmit(product);
                dbContext.SubmitChanges();
                LoadProductsGridView();
                XtraMessageBox.Show("Product Removed!!", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else
            {
                XtraMessageBox.Show("No product found!!", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
    }
}
