<?xml version="1.0" encoding="utf-8"?><Database Name="IslahFactoryInventory" Class="InventoryDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GBBLD7C\SQLEXPRESS;Initial Catalog=IslahFactoryInventory;Integrated Security=True;Connect Timeout=30;TrustServerCertificate=True" SettingsObjectName="IslahGroupInventory.Properties.Settings" SettingsPropertyName="IslahFactoryInventoryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Branch" Member="Branches">
    <Type Name="Branch">
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BranchName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPerson" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Branch_Customer" Member="Customers" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Customer" />
      <Association Name="Branch_IGUser" Member="IGUsers" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="IGUser" />
      <Association Name="Branch_Invoice" Member="Invoices" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Invoice" />
      <Association Name="Branch_Log" Member="Logs" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Log" />
      <Association Name="Branch_Product" Member="Products" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Product" />
      <Association Name="Branch_Purchase" Member="Purchases" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Purchase" />
      <Association Name="Branch_Service" Member="Services" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Service" />
      <Association Name="Branch_Supplier" Member="Suppliers" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Supplier" />
      <Association Name="Branch_Voucher" Member="Vouchers" ThisKey="BranchId" OtherKey="Branch_BranchId" Type="Voucher" />
    </Type>
  </Table>
  <Table Name="dbo.VoucherItem" Member="VoucherItems">
    <Type Name="VoucherItem">
      <Column Name="VIIid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Voucher_VoucId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Voucher_VoucherItem" Member="Voucher" ThisKey="Voucher_VoucId" OtherKey="VoucId" Type="Voucher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Category_SubCategory" Member="SubCategories" ThisKey="Name" OtherKey="Category_Name" Type="SubCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CustName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Invoice" Member="Invoices" ThisKey="CustId" OtherKey="Customer_CustId" Type="Invoice" />
      <Association Name="Customer_Service" Member="Services" ThisKey="CustId" OtherKey="Customer_CustId" Type="Service" />
      <Association Name="Branch_Customer" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IGUser" Member="IGUsers">
    <Type Name="IGUser">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AName" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="AUsername" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APassword" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="UserType_UsrType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="IGUser_Log" Member="Logs" ThisKey="UserId" OtherKey="IGUser_UserId" Type="Log" />
      <Association Name="Branch_IGUser" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
      <Association Name="UserType_IGUser" Member="UserType" ThisKey="UserType_UsrType" OtherKey="UsrType" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvcId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvcCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="InvcDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Due" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Customer_CustId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentType_PType" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceItem" Member="InvoiceItems" ThisKey="InvcId" OtherKey="Invoice_InvcId" Type="InvoiceItem" />
      <Association Name="Branch_Invoice" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
      <Association Name="Customer_Invoice" Member="Customer" ThisKey="Customer_CustId" OtherKey="CustId" Type="Customer" IsForeignKey="true" />
      <Association Name="PaymentType_Invoice" Member="PaymentType" ThisKey="PaymentType_PType" OtherKey="PType" Type="PaymentType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceItem" Member="InvoiceItems">
    <Type Name="InvoiceItem">
      <Column Name="Invoice_InvcId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Product_ProdId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceItem" Member="Invoice" ThisKey="Invoice_InvcId" OtherKey="InvcId" Type="Invoice" IsForeignKey="true" />
      <Association Name="Product_InvoiceItem" Member="Product" ThisKey="Product_ProdId" OtherKey="ProdId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="LogId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LogType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LogTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IGUser_UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Branch_Log" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
      <Association Name="IGUser_Log" Member="IGUser" ThisKey="IGUser_UserId" OtherKey="UserId" Type="IGUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentType" Member="PaymentTypes">
    <Type Name="PaymentType">
      <Column Name="PType" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PaymentType_Invoice" Member="Invoices" ThisKey="PType" OtherKey="PaymentType_PType" Type="Invoice" />
      <Association Name="PaymentType_Purchase" Member="Purchases" ThisKey="PType" OtherKey="PaymentType_PType" Type="Purchase" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProdId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProdCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ProdName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ReOrderPoint" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubCategory_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_InvoiceItem" Member="InvoiceItems" ThisKey="ProdId" OtherKey="Product_ProdId" Type="InvoiceItem" />
      <Association Name="Branch_Product" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
      <Association Name="SubCategory_Product" Member="SubCategory" ThisKey="SubCategory_Name" OtherKey="Name" Type="SubCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchase" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="PurcId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurcCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PurcDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Purchaser" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Due" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Supplier_SuppId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentType_PType" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Purchase_PurchaseItem" Member="PurchaseItems" ThisKey="PurcId" OtherKey="Purchase_PurcId" Type="PurchaseItem" />
      <Association Name="Branch_Purchase" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
      <Association Name="PaymentType_Purchase" Member="PaymentType" ThisKey="PaymentType_PType" OtherKey="PType" Type="PaymentType" IsForeignKey="true" />
      <Association Name="Supplier_Purchase" Member="Supplier" ThisKey="Supplier_SuppId" OtherKey="SuppId" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseItem" Member="PurchaseItems">
    <Type Name="PurchaseItem">
      <Column Name="ItemId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Purchase_PurcId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Purchase_PurchaseItem" Member="Purchase" ThisKey="Purchase_PurcId" OtherKey="PurcId" Type="Purchase" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Service" Member="Services">
    <Type Name="Service">
      <Column Name="ServId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EstDeliveryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalCharge" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Customer_CustId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceType_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Service_ServiceItem" Member="ServiceItems" ThisKey="ServId" OtherKey="Service_ServId" Type="ServiceItem" />
      <Association Name="Branch_Service" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
      <Association Name="Customer_Service" Member="Customer" ThisKey="Customer_CustId" OtherKey="CustId" Type="Customer" IsForeignKey="true" />
      <Association Name="ServiceType_Service" Member="ServiceType" ThisKey="ServiceType_Name" OtherKey="Name" Type="ServiceType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceItem" Member="ServiceItems">
    <Type Name="ServiceItem">
      <Column Name="SIId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceDetails" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Charge" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Service_ServId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Service_ServiceItem" Member="Service" ThisKey="Service_ServId" OtherKey="ServId" Type="Service" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceType" Member="ServiceTypes">
    <Type Name="ServiceType">
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ServiceType_Service" Member="Services" ThisKey="Name" OtherKey="ServiceType_Name" Type="Service" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SuppId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SuppCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SuppName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Supplier_Purchase" Member="Purchases" ThisKey="SuppId" OtherKey="Supplier_SuppId" Type="Purchase" />
      <Association Name="Branch_Supplier" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserType" Member="UserTypes">
    <Type Name="UserType">
      <Column Name="UsrType" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserType_IGUser" Member="IGUsers" ThisKey="UsrType" OtherKey="UserType_UsrType" Type="IGUser" />
    </Type>
  </Table>
  <Table Name="dbo.Voucher" Member="Vouchers">
    <Type Name="Voucher">
      <Column Name="VoucId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VoucCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="VoucDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Branch_BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Voucher_VoucherItem" Member="VoucherItems" ThisKey="VoucId" OtherKey="Voucher_VoucId" Type="VoucherItem" />
      <Association Name="Branch_Voucher" Member="Branch" ThisKey="Branch_BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubCategory" Member="SubCategories">
    <Type Name="SubCategory">
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Category_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Category_Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="SubCategory_Product" Member="Products" ThisKey="Name" OtherKey="SubCategory_Name" Type="Product" />
      <Association Name="Category_SubCategory" Member="Category" ThisKey="Category_Name" OtherKey="Name" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>